
// ------------------------------------------
// MINER

export const MINER_INFO = {
  REQUESTED: 'MINER_INFO_REQUESTED',
  SUCCEDED : 'MINER_INFO_SUCCEDED',
  FAILED   : 'MINER_INFO_FAILED'
}

export const UPDATE_MINING = {
  REQUESTED: 'UPDATE_MINING_REQUESTED',
  SUCCEDED : 'UPDATE_MINING_SUCCEDED',
  FAILED   : 'UPDATE_MINING_FAILED'
}

// ------------------------------------------
// BLOCKCHAIN

export const BLOCKCHAIN_INFO = {
  REQUESTED: 'BLOCKCHAIN_INFO_REQUESTED',
  SUCCEDED : 'BLOCKCHAIN_INFO_SUCCEDED',
  FAILED   : 'BLOCKCHAIN_INFO_FAILED'
}
